### ISSUE TITLE
Incorrect dependency data on rspec old releases

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems.org#1906]
I noticed that the dependency data on old RSpec releases does not seem correct. For example,

#### `curl https://rubygems.org/api/v2/rubygems/rspec/versions/1.2.3.json | jq`

Rubygems.org considers `hoe` and `cucumber` as runtime dependencies of RSpec.

```JSON
{
  "name": "rspec",
  "downloads": 367815598,
  "version": "1.2.3",
  "version_downloads": 2736,
  "platform": "ruby",
  "authors": "RSpec Development Team",
  "info": "Behaviour Driven Development for Ruby.",
  "licenses": null,
  "metadata": {},
  "sha": "2d95a5af310bf7aa0db7f1b33ee54cef33f9c843f5c91791af8bf072587825c5",
  "project_uri": "https://rubygems.org/gems/rspec",
  "gem_uri": "https://rubygems.org/gems/rspec-1.2.3.gem",
  "homepage_uri": "http://github.com/rspec",
  "wiki_uri": "",
  "documentation_uri": "http://relishapp.com/rspec",
  "mailing_list_uri": "http://rubyforge.org/mailman/listinfo/rspec-users",
  "source_code_uri": "http://github.com/rspec/rspec",
  "bug_tracker_uri": "",
  "changelog_uri": null,
  "dependencies": {
    "development": [
      {
        "name": "cucumber",
        "requirements": ">= 0.2.2"
      },
      {
        "name": "hoe",
        "requirements": ">= 1.12.1"
      }
    ],
    "runtime": [
      {
        "name": "cucumber",
        "requirements": ">= 0.2.2"
      },
      {
        "name": "hoe",
        "requirements": ">= 1.12.1"
      }
    ]
  },
  "built_at": "2009-04-13T03:00:00.000Z",
  "created_at": "2009-07-25T17:56:42.000Z",
  "description": "Behaviour Driven Development for Ruby.",
  "downloads_count": 2736,
  "number": "1.2.3",
  "summary": "rspec 1.2.3",
  "rubygems_version": ">= 0",
  "ruby_version": null,
  "prerelease": false,
  "requirements": null
}
```

However, if I look for the gemspec using the `gem` client, I see they are only development dependencies

#### `gem specification --remote -v 1.2.3 rspec`

```YAML
--- !ruby/object:Gem::Specification
name: rspec
version: !ruby/object:Gem::Version
  version: 1.2.3
platform: ruby
authors:
- RSpec Development Team
autorequire: 
bindir: bin
cert_chain: []
date: 2009-04-13 00:00:00.000000000 Z
dependencies:
- !ruby/object:Gem::Dependency
  name: cucumber
  type: :development
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 0.2.2
  version_requirement: 
- !ruby/object:Gem::Dependency
  name: hoe
  type: :development
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 1.12.1
  version_requirement: 
description: Behaviour Driven Development for Ruby.
email:
- rspec-devel@rubyforge.org
executables: []
extensions: []
extra_rdoc_files: []
files: []
homepage: http://rspec.info
licenses: []
metadata: 
post_install_message: 
rdoc_options: []
require_paths:
- lib
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
required_rubygems_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
requirements: []
rubygems_version: 3.0.2
signing_key: 
specification_version: 2
summary: rspec 1.2.3
test_files: []
```

This is causing `bundler` to make unnecessary requests to `rubygems.org` when running `bundle install`. See https://github.com/bundler/bundler/issues/6914.

If we find out the root cause of this we could probably run a script to fix all affected data. Any ideas welcome!
