### ISSUE TITLE
At least one gemspec has incorrect dependency data as an array of arrays

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems.org#2329]
The gem in question is `ajp-rails` version `0.0.0`, which has the dependencies property in its gemspec set to an array of arrays.

This makes the gem uninstallable:

```
$ gem install ajp-rails -v '0.0.0'
ERROR:  While executing gem ... (NoMethodError)
    undefined method `type' for ["ruby-ajp", ">= 0.2.0"]:Array
```

This is the wrong specification:

#### gem specification ajp-rails -v '0.0.0' --remote 

```yaml
--- !ruby/object:Gem::Specification
name: ajp-rails
version: !ruby/object:Gem::Version
  version: 0.0.0
platform: ruby
authors:
- Yugui
autorequire: 
bindir: bin
cert_chain: []
date: 2006-01-23 00:00:00.000000000 Z
dependencies:
- - ruby-ajp
  - ">= 0.2.0"
- - rails
  - ">= 0.14"
description: ''
email: yugui@yugui.sakura.ne.jp
executables: []
extensions: []
extra_rdoc_files: []
files: []
homepage: 
licenses: []
metadata: 
post_install_message: 
rdoc_options: []
require_paths:
- lib
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: 1.8.3
required_rubygems_version: 
requirements: []
rubygems_version: 3.2.0.pre1
signing_key: 
specification_version: 1
summary: Ruby on Rails Runner, which uses AJP(Apache JServ Protocol) to cooperate
  with a HTTPd, instead of CGI or FastCGI
test_files: []
```

Which was corrected in `0.0.1`

#### gem specification ajp-rails -v '0.0.1' --remote 

```yaml
--- !ruby/object:Gem::Specification
name: ajp-rails
version: !ruby/object:Gem::Version
  version: 0.0.1
platform: ruby
authors:
- Yugui
autorequire: 
bindir: bin
cert_chain: []
date: 2006-01-23 00:00:00.000000000 Z
dependencies:
- !ruby/object:Gem::Dependency
  name: ruby-ajp
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 0.2.0
  version_requirement: 
- !ruby/object:Gem::Dependency
  name: rails
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0.14'
  version_requirement: 
description: ''
email: yugui@yugui.sakura.ne.jp
executables: []
extensions: []
extra_rdoc_files: []
files: []
homepage: 
licenses: []
metadata: 
post_install_message: 
rdoc_options: []
require_paths:
- lib
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: 1.8.3
required_rubygems_version: 
requirements: []
rubygems_version: 3.2.0.pre1
signing_key: 
specification_version: 1
summary: Ruby on Rails Runner, which uses AJP(Apache JServ Protocol) to cooperate
  with a HTTPd, instead of CGI or FastCGI
test_files: []
```

I presume there's a very reduced number of gemspecs with this problem, I assume they were created when a very old rubygems version. It'd be nice to get the data sanitized in this regard.

Thanks!
