### ISSUE TITLE
Backticks in YAML API output crash the Psych parser

### ISSUE THREAD

**Issue by laserlemon** [rubygems/rubygems.org#358]
As of writing this, the mm_to_view_model gem is at version 0.1.1 and its info includes backticks.

https://rubygems.org/api/v1/gems/mm_to_view_model.yaml

``` yaml
--- 
name: mm_to_view_model
dependencies: 
  runtime: 
  - name: mongo_mapper
    requirements: ~> 0.9.2
  development: 
  - name: fuubar
    requirements: ~> 0.0.6
  - name: mocha
    requirements: ~> 0.10.0
  - name: rspec
    requirements: ~> 2.6.0
  - name: watchr
    requirements: ~> 0.7.0
downloads: 5
info: `mm_to_view_model` is a `MongoMapper` plugin that adds a `to_view_model` class and instance method.
version: 0.1.1
version_downloads: 2
homepage_uri: http://github.com/c00lryguy/mm_to_view_model
authors: Ryan Scott Lewis
project_uri: http://rubygems.org/gems/mm_to_view_model
gem_uri: http://rubygems.org/gems/mm_to_view_model-0.1.1.gem
source_code_uri: 
bug_tracker_uri: 
wiki_uri: 
documentation_uri: 
mailing_list_uri: 
```

Meanwhile on the client side, when this is parsed in Ruby 1.8.7 or 1.9.2 using Syck, all is well. But when you parse this YAML with the new Psych parser on Ruby 1.9.2, it bombs, complaining about the backticks. Dumping the same data with Psych changes the `info` line to:

``` yaml
info: ! '`mm_to_view_model` is a `MongoMapper` plugin that adds a `to_view_model` class and instance method.'
```

Syck will load either variation but Psych will only load the latter.

I understand that an upgrade to Ruby 1.9.2 (and Psych) is on the docket  but I thought this issue is worth noting because the `gems` gem uses the YAML API and so `Gems.info("mm_to_view_model")` fails on 1.9.2/Psych.
