### ISSUE TITLE
A few parts of the about page is not properly localized

### ISSUE THREAD

**Issue by nobu** [rubygems/rubygems.org#4042]
A few parts of the [about page] is not properly localized.

[about page]: https://rubygems.org/pages/about

## Steps to Reproduce
1. Access the page above, with locales other than English.

## Expected Behavior

This page should be translated in the target language.

## Current Behavior

[Japanese version page], for instance.

* `.founding_html` paragraph:
  > 2009年4月に[Nick Quaranto](https://twitter.com/qrush)の手によって発足したプロジェクトは、現在[350 Rubyists](https://github.com/rubygems/rubygems.org/graphs/contributors)の貢献を得て[millions of gem downloads](https://rubygems.org/stats)に到るまで成長を遂げました。

  As you can see, the linked phrases are not translated.
  The first part is a proper noun and ok of course.
  But ["350 Rubyists"] and ["millions of gem downloads"] are not.

* `. technical_html` paragraph:
  > このサイトの技術的な側面に目を向けるなら、100% Rubyでできています。サイトの主要な部分は[Rails](https://rubyonrails.org/)アプリケーションです。gemは[Amazon S3](https://aws.amazon.com/s3/)上にホストされ、[Fastly](https://www.fastly.com/)によりサーブされており、新しく公開したgemがインストール可能になるまで通常はほんの数秒です。詳細は[please check out the code](https://github.com/rubygems/rubygems.org)。GitHub上で[MIT licensed](https://www.opensource.org/licenses/mit-license.php)となっています。

  The phrase ["please check out the code"] is not translated.
  ["MIT licensed"] is a subtle as a translation too, since the phrase is an adjective while the link target is a noun.

* Also, [about__assets__heading] is not translated at all.

[Japanese version page]: https://rubygems.org/pages/about?locale=ja
["350 Rubyists"]: https://github.com/rubygems/rubygems.org/blob/deada256ee6fad48a3766a34affa08a1560389e4/app/views/pages/about.html.erb#L12
["millions of gem downloads"]: https://github.com/rubygems/rubygems.org/blob/deada256ee6fad48a3766a34affa08a1560389e4/app/views/pages/about.html.erb#L13
["please check out the code"]: https://github.com/rubygems/rubygems.org/blob/deada256ee6fad48a3766a34affa08a1560389e4/app/views/pages/about.html.erb#L26
["MIT licensed"]: https://github.com/rubygems/rubygems.org/blob/deada256ee6fad48a3766a34affa08a1560389e4/app/views/pages/about.html.erb#L27
[about__assets__heading]: https://github.com/rubygems/rubygems.org/blob/deada256ee6fad48a3766a34affa08a1560389e4/app/views/pages/about.html.erb#L32-L33

## Possible Solution

As for `.founding_html`, I think this would be better:
- "over 350 Rubyists" should be "350人以上のRubyist"
- "millions of gem downloads" should be "何億回ものgemダウンロード"

Note that the order of word "over"("以上") differs in Japanese than English, it can't be placed outside "350 Rubyists".
Or "Rubyist 350人以上" is not wrong, but not better.

## Environment
Browser and its version: any browsers send and handle "Accept-Language" properly.
RubyGems version: unrelated.

**Comment by simi** [comment]
Thanks for the report @nobu. I'll open PR to make those parts "translatable". Once ready, it should be easy to submit PR to fix those problems.

**Comment by simi** [comment]
@nobu those parts reported as not translated are now extracted in separate keys. Would you mind to open PR to translate those?

If that's easier, feel free to just fill in those YAML values and comment back, I'll open PR and handle rest. You can find more context at https://github.com/rubygems/rubygems.org/pull/4063.

```yaml
  pages:
    about:
      contributors_amount:
      downloads_amount:
      checkout_code:
      mit_licensed:
      logo_header:
      logo_details:
```

this is english version for reference

```yaml
  pages:
    about:
      contributors_amount: "%{count} Rubyists"
      downloads_amount: "millions of gem downloads"
      checkout_code: "please check out the code"
      mit_licensed: "MIT licensed"
      logo_header: Looking for our logo?
      logo_details: Just select the download button and you'll get three .PNGs and an .SVG of the RubyGems logo all for yourself.
```
